wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Portland: "America/Los_Angeles"
        New York: "America/New_York"
        UTC: "UTC"
        Moscow: "Europe/Moscow"
        Tokyo: "Pacific/Tokyo"
        New Zealand: "Pacific/Auckland"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
      title: "Clocks"
      type: "clocks"
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    #kubernetes:
    #  enabled: true
    #  kubeconfig: "/Users/spkane/.kube/config"
    #  namespaces:
    #  - default
    #  objects:
    #  - nodes
    #  - pods
    #  position:
    #    top: 0
    #    left: 2
    #    height: 1
    #    width: 1
    #  refreshInterval: 300
    #  title: "K8s"
    feedreader:
      enabled: true
      feeds:
      - http://lwkd.info/feed.xml
      feedLimit: 10
      position:
        top: 1
        left: 1
        width: 2
        height: 1
      updateInterval: 14400
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    gcal:
      colors:
        title: "red"
        eventTime: "lightblue"
        description: "yellow"
        highlights:
        - ['1on1|1\/1|1:1|standup', 'green']
        - ['apple|google|aws|k8s', 'blue']
        - ['interview|meet|call', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "sean@superorbital.io"
      enabled: true
      eventCount: 15
      hourFormat: "24"
      multiCalendar: true
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 300
      secretFile: "~/.calblink/secret.json"
      showDeclined: true
      showEndTime: false
      timezone: "America/Los_Angeles"
      withLocation: true
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 3
        height: 2
        width: 1
      refreshInterval: 3600
    prettyweather:
        enabled: true
        city: "Camas, Washington, USA"
        position:
            top: 2
            left: 3
            height: 2
            width: 1
        refreshInterval: 300
        unit: "u"
        view: 0q
        language: "en"