# Don't print a new line at the start of the prompt
add_newline = false

# use custom prompt order
format = """\
    $env_var\
    $username\
    $hostname\
    $directory\
    $aws\
    $kubernetes\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $helm\
    $dotnet\
    $golang\
    $conda\
    $java\
    $nodejs\
    $python\
    $ruby\
    $rust\
    $terraform\
    $nix_shell\
    $memory_usage\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """

# Wait 30 milliseconds for starship to check files under the current directory.
scan_timeout    = 30
command_timeout = 1000

[aws]
format = '[$symbol $profile\($region\)]($style) '
style = '#668cff'
symbol = '🅰'

[aws.region_aliases]
us-east-1 = 'use1'
us-east-2 = 'use2'
us-west-1 = 'usw1'
us-west-2 = 'usw2'

[aws.profile_aliases]
#CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = 'ⓩ '
style = "blue bold"

[azure.subscription_aliases]
# very-long-subscription-name = 'vlsn'

[battery]
disabled = false
full_symbol = ''
charging_symbol = '⚡️'
discharging_symbol = ''
unknown_symbol = ''
empty_symbol = ''
format = '[[ $symbol $percentage ](fg:text bg:crust)]($style)'

[[battery.display]]
threshold = 25
discharging_symbol = ''
style = 'fg:yellow bg:crust'

[[battery.display]]
threshold = 10
discharging_symbol = ''
style = 'fg:peach bg:crust'

[[battery.display]]
threshold = 5
discharging_symbol = ''
style = 'bold fg:red bg:crust'

[conda]
format = '[$symbol$environment](dimmed green) '

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration ]($style)"

[directory]
truncation_length = 3

[directory.substitutions]
"~" = "  "
"Applications" = "  "
"Desktop" = "  "
"Developer" = "  "
"Documents" = " 󰈙 "
"Downloads" = "  "
"Games" = "  "
"GitHub" = "  "
"Library" = "  "
"Movies" = "  "
"Music" = "  "
"Pictures" = "  "
"Projects" = "  "
"Public" = "  "
"Screenshots" = " 󱣴 "
"Videos" = "  "
"Thunderbird" = "   "
"source" = " 󰈹 "
"comm" = "  "

[env_var]
variable = 'PROMPT_ID'
format = '[$env_value]($style)'
default = '🔴'

[gcloud]
format = '[$symbol$active]($style) '
style  = 'bold yellow'
symbol = '️🇬️ '

[gcloud.project_aliases]
#very-long-project-name = 'vlpn'

[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
format = '[$symbol$version]($style)'

[hostname]
ssh_only = true
format = '⟪[$hostname]($style)⟫'
trim_at = '.'
disabled = false

[kubernetes]
format = '[$symbol$user@$context\($namespace\)]($style) '
symbol = '⛵'
style = 'green' 
disabled = false

[[kubernetes.contexts]]
context_pattern = 'arn:aws:eks:[^:]+:\d+:cluster/(?P<cluster>.+)'
style = "bold red"
context_alias = "$cluster"
user_alias = "sean"

[nodejs]
symbol = "☊"

[python]
format = '[${symbol}${pyenv_prefix}${version}(-$virtualenv)]($style) '
style = 'yellow'

[ruby]
format = '[$symbol$version]($style) '

[status]
symbol = '  '
success_symbol = '  '
not_executable_symbol = '  '
not_found_symbol = '  '
map_symbol = true
disabled = false
style = 'fg:text bg:surface0'
format = '[$symbol]($style)'

[os]
format = '[ $symbol]($style)'
style = 'fg:lavender bg:crust'
disabled = false

[os.symbols]
Arch = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Linux = " "
Macos = " "
NixOS = "󱄅 "
Nobara = " "
Pop = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "

[username]
disabled = true

